version = 1

test_patterns = [
  'tests/**'
]

[[analyzers]]
  name = "python"
  enabled  = true

  [analyzers.meta]
  max_line_length = 100
  skip_doc_coverage = ["module", "magic", "class"]

[[analyzers]]
  name = "test-coverage"
  enabled = true
