sudo: false

language: python

cache: pip

python: "3.6"

env:
  matrix:
   - TOXENV=py27-django111
   - TOXENV=py34-django111
   - TOXENV=py35-django111
   - TOXENV=py36-django111
   - TOXENV=py34-django20
   - TOXENV=py35-django20
   - TOXENV=py36-django20
   - TOXENV=py35-django21
   - TOXENV=py36-django21
   - TOXENV=py36-djangomaster

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.5"
      env: TOXENV=py35-django21
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py35-django21
  allow_failures:
    - env: TOXENV=py36-djangomaster

install:
  - pip install tox
  - pip install tox-travis
  - pip install coverage

script:
  - tox

after_success:
  - coverage xml
  - curl https://deepsource.io/cli | sh
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
